#!/usr/bin/env ruby
require './DictionaryProcesses'


# Initialize variables
min = 0
max = 0
charset = nil
fileName = nil
pattern = nil
lang = nil


# Fetching Arguments From Console
ARGV.length.times do |i|
	if ARGV[i] == "-m" or ARGV[i] == "--min"
		min = ARGV[i+1]
	elsif ARGV[i] == "-M" or ARGV[i] == "--max"
		max = ARGV[i+1]
	elsif ARGV[i] == "-c" or ARGV[i] == "--charset"
		charset = ARGV[i+1]
	elsif ARGV[i] == "-o" or ARGV[i] == "--fileName"
		fileName = ARGV[i+1]
	elsif ARGV[i] == "-l" or ARGV[i] == "--language"
		lang = ARGV[i+1]
	elsif ARGV[i] == "-h" or ARGV[i] == "--help"
		DictionaryProcesses.helpMenu
	elsif ARGV[i] == "-p" or ARGV[i] == "--pattern"
		pattern = ARGV[i+1]  # Sadece yıldız (*****) girince maalesef sorun çıkıyor. Diğer türlü sorun yok. 
	end
end


# Default Values
if charset.nil?
	charset = "alphabetSet"
end
if fileName.nil?
	fileName = "sozluk"
end
if lang.nil?
	lang = "tureng"
end



# Audits
if ARGV.length == 0
	DictionaryProcesses.helpMenu
	exit
end
if min > max
	raise DictionaryProcesses.errorMessage
	exit
end
if fileName.include? "."
	fileName = fileName.split('.')[0]
end



# Open File
file = File.open("#{fileName}.txt", "a+")

# Create Wordlist
if pattern.nil?
	DictionaryProcesses.createWordlist(file, min, max, charset, lang)
else
	DictionaryProcesses.createWordlistByUsingRegExp(file, pattern, charset, lang)
end

# Close file
file.close





=begin

turWordlist <min> <max> <charset> <filename>


turWordlist --minimum <min> --maksimum <max> --karakterListesi <charset> --dosya <filename>

=end



=begin
	About Threads
	========================================================================
	Thread begins running automatically when CPU resources become available.
	

	========================================================================
=end